version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: curl -X POST "https://api.testproject.io/v2/projects/-VKPLWYr10C9_ZT_5tLjOA/tests/UKAgVXbepk6mBksp5yC5mA/run" -H "accept: application/json" -H "Authorization: ng840FiIYQgh_mvaBmrmpompfgTc16m2SiTZ0ft3nB81" -H "Content-Type: application/json" -d "{ \"agentId\": \"YjEQcnqq7kGJYTh4vBrfPg\", \"browser\": \"Chrome\", \"queue\": true, \"testParameters\": { \"ApplicationURL\": \"https://booking.com\", \"Location\": \"Dead Sea\", \"in\": \"10\", \"out\": \"15\" }}"
          name: Run test on Build

workflows:
  main:
    jobs:
      - build-and-test
