version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build-env:
    executor: python/default
    steps:
      - checkout
  run-recorded-tests:
    executor: python/default
    steps:
     - run:
          command: curl -X POST "https://api.testproject.io/v2/projects/-VKPLWYr10C9_ZT_5tLjOA/jobs/E9wd6FJiRUu_ZkzD9e-qww/run" -H "accept:application/json" -H "Authorization:ng840FiIYQgh_mvaBmrmpompfgTc16m2SiTZ0ft3nB81" -H "Content-Type:application/json" -d "{ \"agentId\":\"YjEQcnqq7kGJYTh4vBrfPg\", \"browsers\":[ \"Chrome\", \"Edge\", \"Safari\" ], \"queue\":true, \"restartDriver\":false, \"testParameters\":[ { \"testId\":\"UKAgVXbepk6mBksp5yC5mA\", \"data\":[ { \"Location\":\"Dead Sea\", \"in\":\"10\", \"out\":\"15\" } ] } ]}"
          name: Run Test On Build
workflows:
  main:
    jobs:
      - build-env
      - run-recorded-tests